### ISSUE TITLE
Onedrive can not read if this add-on is valid

### ISSUE THREAD

**Issue by Geckomaskman** [idlewan/javascript-control#2]
Even if you enable this add-on, you can not load the Onedrive site. Even though it is effective, it blocks some Javascript arbitrarily.
https://onedrive.live.com/
--

**Comment by idlewan** [comment]
Indeed, it's because onedrive relies on iframes for its site to function.
I successfully logged in by enabling js on  `live.com` pages that you're redirected to when logging in, then had access to onedrive's main screen but files weren't loading.
Go to https://skyapi.onedrive.live.com/xmlproxy.htm?domain=live.com  (that's the address of the iframe needed by onedrive) and enable javascript, then reload the page and files should appear.

The problem happens because even though you enabled javascript for the main site, all of the iframes on the site need to have js enabled also.

**Comment by idlewan** [comment]
I can fix this, at the cost of having youtube videos embedded on other pages (or other embeds that have been allowed to use js on their own site) to stop working until javascript is enabled for the page.
Might be a good trade-off.

**Comment by idlewan** [comment]
Should be fixed in `v1.1`.

**Comment by Geckomaskman** [comment]
Thank you. I expect it.
